# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game_type', models.CharField(choices=[('SP', 'Simple play'), ('MP', 'Multyplay')], max_length=3)),
                ('data_begin', models.DateField(auto_now=True)),
                ('data_end', models.DateField(blank=True)),
            ],
        ),
    ]
